name: Amplified Administration
favicon: null
layout_spectrum: 0.53513
typography_spectrum: 0.33293
title: Amplified Administration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c58a30'
    - '#51170b'
    - '#dab57e'
    - '#5f3d38'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
