name: Amplified Administration
favicon: null
layout_spectrum: 0.5650439027231187
typography_spectrum: 0.05266187898814678
title: Independent Songwriter and Publisher Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c58a30'
    - '#51170b'
    - '#dab57e'
    - '#5f3d38'
  brandStrength: 0.875
  lightness: 0.4827077994123101
  saturation: 0.5842369184829295
  rhythmicContrast: 0.7543368972837925
purpose: []
